### ISSUE TITLE
Add location code to items

### ISSUE THREAD

**Issue by commgdog** [walnutcreekhardware/som-issues#253]
The item location code is missing from items.

This data is useful for picking items off of the floor.

Adding this will require:

- Adding the location code field to the database for items
- Creating a script to backfill the missing data for existing items
- When adding new items, make sure it is pulling the location code from Eagle for saving in Omni
- The location code should be displayed on the order form

Additional things to consider:

- Location code changes. Should Omni periodically check every item and update location codes for changes?
- Multiple location codes. Some items may have multiple location codes. How is this stored in Eagle? See Peter to see if he has any examples of items with multiple location codes.

**Comment by Daemios** [comment]
Make a script that looks at all open items and refreshes their locations
