### ISSUE TITLE
Add "Vendor Name" to item and order lists

### ISSUE THREAD

**Issue by commgdog** [walnutcreekhardware/som-issues#254]
"Vendor Name" is missing from order and item lists.

This is useful for parsing orders and items that are awaiting ordering.

On order lists, the inventory column shows the status, with a subtext of when the product is expected or when the product was received.

- Research a way to fit the "Vendor Name" in the inventory column of order lists.

On item lists (such as the order form) the inventory column also does not include the "vendor name" when product requires ordering.

- Research a way to fit the "Vendor Name" in the inventory column of item lists (on the order form).

**Comment by Daemios** [comment]
This doesn't seem possible without destroying the (presumably) much more valuable info about arrival date
